development:
  adapter: postgresql
  encoding: unicode
  database: blogging-app-05
  pool: 5
  host: localhost
  username: postgres
  password: annor0543

test:
  adapter: postgresql
  encoding: unicode
  database: blogging-app-test-05
  pool: 5
  username: postgres
  password: annor0543

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 